endpoints:
  - wss://eth-rpc-karura-testnet.aca-staging.network:443

stale_timeout_seconds: 180 # rotate endpoint if no new blocks for 3 minutes

server:
  port: 8545
  listen_address: '0.0.0.0'
  max_connections: 2000

rpcs: ethereum
