extensions:  
  client:
    endpoints:
      - wss://eth-rpc-karura-testnet.aca-staging.network
    health_check:
      interval_sec: 10 # check interval, default is 10s
      healthy_response_time_ms: 500 # max response time to be considered healthy, default is 500ms
      health_method: net_health # eth-rpc-adapter bodhijs
      response: # response contains { isHealthy: true, isRPCOK: true }
        !contains
          - - isHealthy
            - !eq true
          - - isRPCOK
            - !eq true
#      health_method: eth_syncing # eth node
#      response: !eq false
  event_bus:
  eth_api:
    stale_timeout_seconds: 180 # rotate endpoint if no new blocks for 3 minutes
  telemetry:
    provider: none
  cache:
    default_ttl_seconds: 60
    default_size: 500
  server:
    port: 8545
    listen_address: '0.0.0.0'
    max_connections: 2000
    cors: all

middlewares:
  methods:
    - response
    - block_tag
    - cache
    - upstream
  subscriptions:
    - upstream

rpcs: ethereum
