name: Test

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly-2023-09-29
        components: rustfmt, clippy
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Check format
      run: cargo +nightly fmt --all -- --check
    - name: Check clippy
      run: cargo +nightly clippy --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
